### PR TITLE
Pull Request for review

### PR DESCRIPTION
**Pull request by talhawaqar**
- This project uses float.
- This project uses grid and flexbox
- This project uses position property fixes for the navbar and footer

- With the help of this project, we learned all the things mentioned above

### CODE REVIEW

**Review by christianotieno — CHANGES_REQUESTED** [review]
# **CHANGES REQUIRED** :warning:
Hey @emmanuellekamwa & @talhawaqar  :wave:
-
You have done a splendid job! :tada: Keep it up.
We, however, do have some few changes to carry out before we proceed (see review comment).
##
### The [clone](https://rawcdn.githack.com/emmanuellekamwa/Html-positioning-and-floating/364b69874d7293afa6a1b9521e68eab6704000a5/index.html) shows a good understanding and use of positioning and floating of elements in a browser. 💯 

Note that in this project, we have to ensure that nothing is messed up. Kindly see the differences below:
##
## [REQUIRED] - FIX - More in space section.
- - [ ] The section's contents appear more stretched out than normal. Kindly fix that.

|[Clone](https://rawcdn.githack.com/emmanuellekamwa/Html-positioning-and-floating/364b69874d7293afa6a1b9521e68eab6704000a5/index.html)|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|
|:---:|:---:|
|more-in-space-clone|more-in-space|

## [REQUIRED] - FIX - Footer section.
- - [ ] The section's contents are not properly styled and also appear more stretched out than normal more Kindly fix that as well.

|[Clone](https://rawcdn.githack.com/emmanuellekamwa/Html-positioning-and-floating/364b69874d7293afa6a1b9521e68eab6704000a5/index.html)|[Source](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html)|
|:---:|:---:|
|footer-clone|footer|

- If you have any questions, let me know here or on slack and I will be glad to clarify with you. You can also reach me and connect with me on my social media or email. :eyes:
##
- When you have made the specified changes, please submit another code review. Thank you!
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)
---
*P.S. all requested changes not marked by [OPTIONAL] or are not positive comments are **REQUIRED***

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
Hi Team 👋

Your project looks great.🚀

However, kindly make the following fix.

- [x] Please correct the HTML validation errors o your HTML code. Consider using [this tool](https://validator.w3.org/nu/#file) to check and fix the errors.
ice_screenshot_20200512-193722

Kindly fix this issue and request another review👍
Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Review by MarioDena — APPROVED** [review]
Hello team good job on your project, this looks ready to be approved.

## Project approved

Good luck on your next projects!

👍 

## Code review by Mario Enrique Delgado Naranjo

**Pull request merged**
